#pragma once

#define SYSCALL_ID_WAIT 0x10

#define SYSCALL_ID_MALLOC 0x20
#define SYSCALL_ID_FREE 0x21
#define SYSCALL_ID_MEMSET 0x22
#define SYSCALL_ID_MEMCPY 0x23

#define SYSCALL_ID_PRINTF 0x40
#define SYSCALL_ID_PRINTREG 0x41

#define SYSCALL_ID_WINDOW 0xF0