#pragma once

#define SYSCALL_version 2

#define SYSCALL_ID_WAIT 0x10

#define SYSCALL_ID_MALLOC 0x20
#define SYSCALL_ID_FREE 0x21
#define SYSCALL_ID_MEMSET 0x22
#define SYSCALL_ID_MEMCPY 0x23

#define SYSCALL_ID_PRINTF 0x40
#define SYSCALL_ID_PRINTREG 0x41

#define SYSCALL_ID_WINDOW_CREATE 0xF0
#define SYSCALL_ID_WINDOW_CLOSE 0xF1
#define SYSCALL_ID_WINDOW_SET_PIXEL 0xF2
#define SYSCALL_ID_WINDOW_CLEAR 0xF3
#define SYSCALL_ID_WINDOW_IS_VALID 0xF4
#define SYSCALL_ID_WINDOW_UPDATE 0xF5
#define SYSCALL_ID_WINDOW_GET_MOUSE_X 0xF6
#define SYSCALL_ID_WINDOW_GET_MOUSE_Y 0xF7
#define SYSCALL_ID_WINDOW_GET_KEY_STATE 0xF9